type Client{
  id: ID!
  name: String!
  url: String!
  user: ID
  date: String!
  update: String!
}

type History{
  id: ID!
  topic: ID!
  title: String!
  tags: [String!]!
  text: String!
  date: String!
  hash: String!
}

type Msg{
  id: ID!
  receiver: ID
  text: String!
  date: String!
}

type Profile{
  id: ID!
  user: ID
  name: String!
  text: String!
  date: String!
  update: String!
  sn: String!
}

enum VoteFlag{
  uv
  dv
  not
}

interface ResBase{
  id: ID!
  topic: ID!
  date: String!
  user: ID
  uv: Int!
  dv: Int!
  hash: String!
  replyCount: Int!
  voteFlag: VoteFlag
}