type Client{
  id: String!
  name: String!
  url: String!
  user: String
  date: String!
  update: String!
}

type History{
  id: String!
  topic: String!
  title: String!
  tags: [String!]!
  text: String!
  date: String!
  hash: String!
}